@startuml

allow_mixing

class BaseLayout {
  + alarm_placeholder
  + webrtc_ctx

  + video_frame_callback: Callable
  + queued_video_frames_callback: AsyncCallable

  + mount_alarm_placeholder()
  + webrtc_streamer_attributes : WebRtcStreamerAttributes
  + streaming : bool
  + key: str
  {abstract} + mount()
  {abstract} + update()
}

class FireDetectionLayout {
  + mount()
  + update()
}

class FaceIdentificationLayout {
  + mount()
  + update()
}

queue MetadataQueue

BaseLayout <|-- FireDetectionLayout
BaseLayout <|-- FaceIdentificationLayout
BaseLayout o-- MetadataQueue: use >

@enduml